services:
  app:
    container_name: backend-API-Aucto
    build:
      context: . 
    restart: unless-stopped
    depends_on:
      - postgres
      - postgres_test_db
    command: sh -c "./wait && ./bin/app"
    ports:
      - 8080:8080
    environment:
      - WAIT_HOSTS=POSTGRES:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=10
      - WAIT_HOST_CONNECT_TIMEOUT=10

  postgres:
    container_name: aucto-db-1
    platform: linux/x86_64
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER_LOCAL}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_LOCAL}
      POSTGRES_DB: ${POSTGRES_DBNAME_LOCAL}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  postgres_test_db: 
    container_name: aucto-db-test
    platform: linux/x86_64
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
      POSTGRES_DB: ${POSTGRES_DBNAME_TEST}
    ports:
      - '5433:5433'
    command: -p 5433

volumes:
  postgres_data:

    