services:
  app:
    container_name: backend-API-Aucto
    build:
      context: . 
      dockerfile: docker/deploy/Dockerfile
    restart: unless-stopped
    command: sh -c "./wait && ./bin/app"
    ports:
      - 8080:8080

    